city_url: https://newyork.craigslist.org
email: edkharakh@gmail.com
posts:
- id: 7882050961
  title_slug: brooklyn-piano-for-sale
  category: musical instruments
  area: Brooklyn
  postal: 11204
- id: 7882051134
  title_slug: brooklyn-guitar-for-sale
  category: musical instruments
  area: Brooklyn
  postal: 11204
