email: "edkharakh@gmail.com"
city_url: "https://newyork.craigslist.org"

posts:
  - id: 7867090812
    category: computers
    area: Brooklyn
    title_slug: brooklyn-macbook-air-2020
    postal: 11204 # postal/zip code for the post location
