email: edkharakh@gmail.com
city_url: https://newyork.craigslist.org
posts:
- id: 7871439152
  category: musical instruments
  area: Brooklyn
  title_slug: brooklyn-piano-for-sale
  postal: 11204
- id: 7871439262
  category: musical instruments
  area: Brooklyn
  title_slug: brooklyn-guitar-for-sale
  postal: 11204
